### ISSUE TITLE
是否考虑使用SQLite作为数据库，MySQL有些重

### ISSUE THREAD

**Issue by forgaoqiang** [etcd-manage/etcd-manage-server#6]
存储内容视乎有限，是否考虑Sqlite版本

**Comment by shiguanghuxian** [comment]
有准备使用etcd直接存储原数据，最近事情多未做更新，后续会做相应修改，简化依赖

**Comment by forgaoqiang** [comment]
> 有准备使用etcd直接存储原数据，最近事情多未做更新，后续会做相应修改，简化依赖

嗯 etcd也是一个不错的选择
